"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import "react-toastify/dist/ReactToastify.css";
import Header from "@/components/header/Header";
import { ToastContainer } from "react-toastify";

import { Provider } from "react-redux";
import store from "@/components/store/store";


const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>
          <ToastContainer />
          <Header />
          {children}
        </Provider>
      </body>
    </html>
  );
}
