import "./globals.css";
import { Inter } from "next/font/google";
import "react-toastify/dist/ReactToastify.css";
import Header from "@/components/header/Header";
import { ToastContainer } from "react-toastify";
import { AuthUserProvider } from "../../firebase/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <AuthUserProvider> */}
          <ToastContainer />
          <Header />
          {children}
        {/* </AuthUserProvider> */}
      </body>
    </html>
  );
}
